name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v -c release
      - name: Tag
        run: |
          echo ::set-env name=TAG::$(date +'%Y.%m.%d')_${GITHUB_RUN_NUMBER}
          git tag -a $TAG -m "Release $TAG"
          git push origin $TAG
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: .build/release/swift-changelog-parser
          make_latest: "true"
          tagName: ${{ env.TAG }}
