name: Swift

on:
  push:
    tags:
      - "**"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v --disable-sandbox -c release --arch arm64 --arch x86_64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: .build/apple/Products/Release/swift-changelog-parser
          make_latest: "true"
